# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Email
version:      0.01
version_from: Email.pm
installdirs:  site
requires:
    Catalyst:                      2.99
    Email::Send:                   0
    Email::Simple:                 0
    Email::Simple::Creator:        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
